#cloud-config
# Creates a new user named "vpn" with password-less sudo capabilities
# SSH is available on port 4444
#
# Log is saved as /var/log/cloud-init-output.log
#
# OpenVPN is configured automatically and the client certificate is available at /home/vpn/client.ovpn
# Transfer using scp like so:
#     scp -P 4444 vpn@IPADDRESS:/home/vpn/client.ovpn client.ovpn

package_upgrade: true
packages:
  - fail2ban
  - curl
users:
  - name: vpn
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzbbeV122OVlEDsYjj5qXrvt6LYIYFdcLUnZtvcpjGdxQe6X6U3AUkLlBIDMiRGWJf/hjBnYwMEyea9DCaRdyXOSdjPT1pxl7F1Rt9Ws7+fYgO0/3CiI5hW5V6Az0z/8qL41f+YYeIw6CsXqFM7FTl1eFVNOpLAKwTi1+8tkuEvFTNrIVkcMWeKbCryN//SuyFZzmD09h/JBn2aP3XJMadbx+mLf6WkN6r4N9rvSgptQQuI6zPPc2OQLkjqF6LsTt8gC0Lvd4n7B45tk7k976QtdgyGXTL3uLv4DsPJpVTn/aE4GcJLrVKtRtQZYtW4PqWji5Ow6PhcSUXfPwKHKM7Q== Main computer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHNe5ZeyWilBoUNYnYbjNrJeLarNdDYofqVvjmDlsFMXEJH0Ko+sY7ATjXVlR7X++VTft2p4Zar23oKq8YMIJmny5F/Ro3JQxn6lVVNbkyks4a9dPI2gLIBIIS6pSipKHDQbPLfrwnhcjf7DbqLmpOPm6AxeI7SlT/4DCKmLcbBgSZMjT0bOV6J3ccz/ityCTdg0cMvAPejrdl4VBEAFGujOw14hjaiAV98bAmWTP6cnrEdg0ou6VOo6muXa3DUmuLAnoCwlEpzjHEckF60cxT3V9+H05DQIJr8x72JVjBBWW+pZmwbCr3ffUCEcz5eOG85Zr14Dc01RtIFr+oWF8V Prompt on iPad
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvK64To8J0Y+URrB0F+nlT3Hrg67h8Dlu/QYyGbIw2D15Is4kFZaJMKvTSfldr/e0qGljkuoqNhjq7L0/MZUtOwRn1/nHK9uxlFyO1Y4POteWs89AxjuwCjvd3LJyy6FKlBM9EAIQGprvqYF49VYJbnClHe7vqIulfCAHASJc4UlZrlx6SBJsdRmIoBUoHIX3jzkjM7d2ZuTqeg4ApUW+0T8oI9BcO1FC7IP2+zQFdA+KGqSh4tNgwjWfyZwAo1Nv3VntZPVRt0FuRrirDpqyOJPRHipYNxEi9zDLO2Qmqvl4+sczGrkeJfwUuuSDOXJyF/HQ13/JHCkW6os3KWJtX Prompt on iPhone
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
write_files:
  - path: /etc/fail2ban/jail.local
    content: |
        [DEFAULT]
        # Ban hosts for one hour:
        bantime = 3600
        #
        # Override /etc/fail2ban/jail.d/00-firewalld.conf:
        banaction = iptables-multiport
        #
        [sshd]
        enabled = true
        port    = 4444
        logpath = %(sshd_log)s
runcmd:
  # Configure SSH and fail2ban
  - sed -i -e '/^Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers vpn' /etc/ssh/sshd_config
  - sed -i -e '$anospoof on' /etc/host.conf
  - service ssh restart
  - service fail2ban restart
  # Install OpenVPN
  - wget git.io/vgZyn --no-check-certificate -O openvpn-install.sh && bash openvpn-install.sh
  - cp /root/client.ovpn /home/vpn/client.ovpn
